# Rosalind.info challenge "Complementing a String of DNA"
# Given: A DNA string s of length at most 1000 bp.
# Return: The reverse complement of s.
DNA = "CTCACATGGTAGCCAGAGTAATAACCCCTAGGATTACAGGGAGAAATATCGTACCCGTGATACTTTAGTATTAGCGATTCTCAAGGGAGGAGTTGTCGATTCCACCAGTCAAAATCATCCTTGACGTTGATATACCCGATCAGGCTGGCGTACCGGCTAAGAAACCTATCTTGGCGGTCTATTGCGTATACCTTGTACTGTGAAGCACCGGCACTGAATCGAACATCCGGTGTTCACCAGTGCCTTGCGCCAGCCTGAAGTCGAGGCCTTAACTCATGTATGTTCATTCGCGAGACGCCGTATGCAGTAAGGCACGGAACTAGGAAGATACTTGAACAGTACGGGCCTGTACCAGGTGGGAAGTCACATGGGATTAACGCGATACACACCCTAGGTCTGTGTAGCATCGGTCCCATACGCAAGCAGTACTCACCACAAGACCTACCCGCCCCGTCTGATTGAGGTAGCTGCGGGCTCTAGGGAGTAGGTCAAAGCTGTTCATGCAAAGGCCCGCTGCAGGTCAGGGACTTTAAAGCAAATCGAGCAGACGCTTTGCCTAGCCAAAGAATACGTATCGGGCATACATCGTTCACGCTTTCAGTTCAAGTCGGGCGCGAACCTTTGACGTGACTTAGGATGTGTCACACCCCTAGAACCGCGCCTAGTCACCACGATGTTGGGTCGACACCGGAAGCGTCCGGCGACTAGAGGGACTTTTACAGTTCTGCCACTTAATTTACTACGCACAAGTAAAATTTATACCAAACCCGTGCAAGGCTAGAACTGATGCCTGTCCAAGCTCGGAGCATAAGAGCATTCAGCCTGCGTCTCTTCGTGCCTCGGCCCTACTACCACATCAGCGTCTTTGAGTCACTACCCGAGCCAAGATGGCAACGATACAGAGATTAACCTCGGGTTTTCCCTTTGCGGCCTTGTCTGGGTTAACAGTG"
transcription = ""

# Transcription
for nuc in DNA:
    if nuc == "A":
        transcription += ("T")
    elif nuc == "T":
        transcription += ("A")
    elif nuc == "C":
        transcription += ("G")
    elif nuc == "G":
        transcription += ("C")
# Check if transcription worked
print(transcription)

#Create reverse compliment
rc = transcription[::-1] #slicing method
print(rc)