# Rosalind challenge - Transcribing DNA into RNA
# Given: A DNA string t having length at most 1000 nt.
# Return: Return: The transcribed RNA string of t.
RNA = ""
DNA = "GTCCTGTCTCGGCCTGGAGTTTTGCTACTCGGAACGCACCTAACGACCATTGTCGAGTTTCCTTAAAAGAAGTGCGCGTACGTAACGAAGAACATTTACATACAGATCATTTCGTGTTGTACGCCTCCAATGCTTATTAAAGCTCTCCGGCGGTTGGGAGAATGATTATATTTGTTAGCTTGATCTCATCCCCAATAAACGCATTGGCCCCCGTACGCCTTGGGGAAACTGTGCAGCGGGCTATAGTTCCTTTACGGATCAATATCTATCTATGGGGATCGACCAATCGTGGACCACGGCAGAGACAAGAGCGCATTCCATAGGTGGACCCACGTAGTCCGCTTCTGTAGATCGTTTACCGAACATCTAGTAGCAGTCTGAGTGAGCGGTCCTTCTTGGACGCGCAATCACGGTGGATCTTCGTGCCCTTAGCTGGTTGCTCTGTTGCGCCATTACTTTTGTGCGCCGACCCGTAGTATTCTCGTATGTGCGTGAAGACTTAAACTACAGACCAAATCTCTAAGCCGCGCCCTTCGGGTAATAGTAAATGGAAGTATTGGGAATTGTAAAATTTCATTGTAACTTCAAGCAAATTATTGCCGGGGACATCAACGCGCGATATTCGACAAGAGTCCACGGCCCGGGCGTCAACGCTCCTTAGCCGATAGACCGACCCGTGCAGCAAGGCCAGCCATTTCAGCAAGACACGACGCCCTCGACAAACTTTGCAGTTTTTGGAGCCGAAGACACTCATATGTGCTCTGAGGCCATGAATAGACCTGGTTCCAGCGAATTTTCCCTATGGCATTCTATGCTCTCGCACGGAAAGGAACTATTCGACATTTGTGGGATAGGGTCGACGCCAGCATTTCAAAGACACTACACTCGATTTAAAGCGCTGGCCCTGCCAGAGGCTGTTTGAATTCAACCTATGCGAACGTTCCACACTAAGTGC"

for nucs in DNA:
    if nucs == "T":
        print("U")
        RNA += "U"
    elif nucs == "A":
        print("A")
        RNA += "A"
    elif nucs == "C":
        print("C")
        RNA += "C"
    else:
        print("G")
        RNA += "G"

print(RNA)
